module.exports = [
  {
    id: '50_percent',
    name: '50 percent',
    duration: 'forever',
    currency: null,
    metadata: {},
    amount_off: null,
    duration_in_months: null,
    percent_off: 50,
    max_redemptions: 50,
    redeem_by: null,
  },
  {
    id: '5_off',
    name: '$5 off',
    duration: 'repeating',
    currency: 'usd',
    metadata: {},
    amount_off: 500,
    duration_in_months: 6,
    percent_off: null,
    max_redemptions: 30,
    redeem_by: null,
  },
  {
    id: 'expired',
    name: 'Expired',
    duration: 'once',
    currency: null,
    metadata: {},
    amount_off: null,
    duration_in_months: 6,
    percent_off: 25,
    max_redemptions: null,
    redeem_by: 1577750400,
  },
  {
    id: 'canadian',
    name: 'Canadian Coupon',
    duration: 'forever',
    currency: 'cad',
    metadata: {},
    amount_off: 550,
    duration_in_months: null,
    percent_off: null,
    max_redemptions: null,
    redeem_by: null,
  },
];
